[package]
name = "solver"
version = "0.1.0"
authors = ["William Rieger <wrieger@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
deunicode = "1.2.0"
wasm-bindgen = "0.2.73"
