[package]
name = "solver-wasm"
version = "0.1.0"
authors = ["Billy Rieger <wrieger@protonmail.com>"]
edition = "2018"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
solver-lib = { path = "../lib" }
wasm-bindgen = "0.2.73"
